version: '3.8'

services:
  damm-postgres:
    image: postgres:15
    container_name: damm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: damm_admin
      POSTGRES_PASSWORD: damm_password
      POSTGRES_DB: damm_db
      TZ: Asia/Seoul
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always