# ==========================================
# [Main Application Configuration]
# ==========================================
spring.application.name=damm-api
server.port=8080

# 분할된 설정 파일들을 불러옵니다. (db, oauth, api)
# 이렇게 하면 application-db.properties, application-oauth.properties 등을 자동 병합합니다.
spring.profiles.include=db, oauth, api

# 현재 실행 환경 프로필 지정 (나중에 운영 서버 배포 시 prod로 변경)
spring.profiles.active=local

file.upload-dir=./uploads/images
file.access-path=/view/